name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2


    # Install dependencies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # Caching
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

    - name: Install dependencies
      run: |
        pip install -r ./docs/requirements.txt --upgrade --upgrade-strategy eager
      
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build docs

    - name: Moving slides to static HTML
      run: |
        sh ./shell/copy_slides.sh

    # # NMC talk
    # - name: Copy static PDF
    #   uses: canastro/copy-file-action@master
    #   with: 
    #     source: docs/slides/nmc.pdf
    #     target: docs/_build/html/nmc.pdf

    # # Lab meeting talk
    # - name: Copy static HTML
    #   uses: canastro/copy-file-action@master
    #   with: 
    #     source: docs/slides/lab-meeting-2022-02-24/lab-meeting-2022-02-24.html
    #     target: docs/_build/html/lab-meeting-2022-02-24.html
      
    # - name: Copy static PDF
    #   uses: canastro/copy-file-action@master
    #   with: 
    #     source: docs/slides/lab-meeting-2022-02-24/lab-meeting-2022-02-24.pdf
    #     target: docs/_build/html/lab-meeting-2022-02-24.pdf

    # # Drexel talk
    # - name: Copy static PDF
    #   uses: canastro/copy-file-action@master
    #   with: 
    #     source: docs/slides/drexel/drexel.pdf
    #     target: docs/_build/html/drexel.pdf

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html